### PR TITLE
nwchem 7.0.0 cleanup

### PR DESCRIPTION
**Pull request by marcindulak**
Cleanup of the nwchem-7.0.0 spec. Note that the build still fails on epel6 - could you check this?

- I've switched to always download the `git_hash` as the source, dropping other variables.
This will allow us to build any hash, and hopefully make the name and the top-level directory of the tarball fixed.

- it seems like epel6 builds fail with `python-config not found in your PATH` https://koji.fedoraproject.org/koji/taskinfo?taskID=38076852
Setting PYTHONVERSION explicitly does not seem to fix this https://github.com/marcindulak/fedpkg/commit/16550eecef9eb0810554c0b336f2ffb48bd97728#diff-28d6bdd5822e780f45a53b340cc5d6acR25

- removing all ga https://github.com/marcindulak/fedpkg/commit/16550eecef9eb0810554c0b336f2ffb48bd97728#diff-28d6bdd5822e780f45a53b340cc5d6acR185

- cleanup the commented out macros - note that in the spec one needs to use `%%` in order for a macro to not be evaluated https://rpm-packaging-guide.github.io/#defining-your-own

*Note** that after the epel6 build is fixed we need to switch back to the ga 5.6.5-3 dependency in the spec https://github.com/marcindulak/fedpkg/commit/16550eecef9eb0810554c0b336f2ffb48bd97728#diff-28d6bdd5822e780f45a53b340cc5d6acR10

### CODE REVIEW

**Review by edoapra — CHANGES_REQUESTED** [review]
PYTHONHOME and USE_PYTHONCONFIG are gone
python3.?-devel should contain python-config or python3-config, am I right? 
This is what I get on a rhel6 box (is this the same as epel6?)
```
lsb_release -r
Release:	6.10
$ rpm -q -l python-devel|grep "python\-config"
/usr/bin/python-config
/usr/bin/python-config
rpm -q -l python34-devel|grep "python3\-config"
/usr/bin/python3-config
/usr/bin/python3-config
```
I would stick to the 5.6.5-3 requirement for ga (it contains an important bug fix).
What is blocking the epel rpms update to 5.6.5-3?

**Comment by marcindulak** [comment]
5.6.5-3 apparently was never built on epel6 - can you give it "karma" https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-e0b05663a1

https://github.com/nwchemgit/nwchem/commit/bd4e66779e54349b0331437918d5a075c79b1d76
- on epel6, python2 and /usr/bin/python-config are present, but not /usr/bin/python2-config, it's actually make clean that fails https://koji.fedoraproject.org/koji/taskinfo?taskID=38076852

```
+ /usr/bin/make clean
python-config not found in your PATH
```

**Comment by edoapra** [comment]
@marcindulak 

I have applied karma to the epel6 (and epel7, could not find one for epel8) ga rpm.
I have pushed a fix for the make clean/python-config problem to the release/7-0-0 branch https://github.com/nwchemgit/nwchem/commit/1c5f20f85040651743cc18e9672c87a6d11deb66
The current fedpkg tree now contains your changes and point to the current 7.0.0 source  https://github.com/edoapra/fedpkg/commit/8b4296851f9edae8ad38c7bc680478297ec141cb

Initial testing on koji seems encouraging

**Comment by marcindulak** [comment]
We still need the ga-5.6.5-3 change in the spec

**Comment by edoapra** [comment]
> 
> 
> We still need the ga-5.6.5-3 change in the spec

Pushed 
85ba191fd189ebac2a341683b1aefe36db04ba5d

**Pull request merged**
